# Docker compose syntax version
version: "3.9"

services:
  # Name of the service
  app:
    # Build docker file in current directory (.)
    build:
      context: .
      args:
        - DEV=true
    # Port mapping. Map local port 8000 to port 8000 inside docker container (local:container)
    ports:
      - "8000:8000"
    # Mapping local directory to container directory (local:container)
    # so local and container code is in sync and dont need to build everytime to update code
    volumes:
      - ./app:/app
    # Command used to run this service can overwrite using "docker-compose run"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db # Name of db service
      - DB_NAME=devdb # Name of database
      - DB_USER=devuser # Database user name
      - DB_PASS=password123 # User password
    depends_on:
      - db # App service depends on db service therefore app will wait for db to start before starting itself

  # Name of second service
  db:
    image: postgres:13-alpine
    # Create volume in container using the volume specified below
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      # Create new database
      - POSTGRES_DB=devdb # name of the database
      - POSTGRES_USER=devuser # User
      - POSTGRES_PASSWORD=password123 # Password for database

volumes:
  # name of volume
  dev-db-data:
